version: '3.8'

# Override configuration for DigitalOcean server deployment
# This ensures all services use the same database path

services:
  orchestrator:
    image: mnemo_orchestrator:latest
    ports:
      - "80:8080"
    environment:
      - DATABASE_TYPE=sqlite
      - DATABASE_PATH=/data/video_memory.db  # Absolute path!
      - ORCHESTRATOR_PORT=8080
      - LOG_LEVEL=info
    volumes:
      - ~/Mnemo/data:/data  # Mount data directory
    restart: unless-stopped
    
  video-worker:
    image: mnemo_video_worker:latest
    environment:
      - DATABASE_PATH=/data/video_memory.db
      - LOG_LEVEL=info
    volumes:
      - ~/Mnemo/data:/data  # Same data directory
    restart: unless-stopped
    depends_on:
      - orchestrator
    deploy:
      resources:
        limits:
          memory: 800M
          cpus: '0.5'
          
  motion-extractor:
    image: mnemo_motion_extractor:latest
    environment:
      - DATABASE_PATH=/data/video_memory.db
      - LOG_LEVEL=info
    volumes:
      - ~/Mnemo/data:/data
      - /tmp/mnemo_work:/tmp/mnemo_work  # Access to extracted frames
    restart: unless-stopped
    depends_on:
      - video-worker
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'