version: '3.8'

# Optimized configuration for DigitalOcean 2GB server deployment
# Compatible with both Docker and Podman
# Total memory usage: ~1.4GB (leaves 600MB for OS)
#
# Usage with Podman:
#   podman-compose -f docker-compose.server.yml --env-file .env.server up -d
#
# Usage with Docker:
#   docker-compose -f docker-compose.server.yml --env-file .env.server up -d

services:
  orchestrator:
    image: mnemo_orchestrator:latest
    ports:
      - "80:8080"
    environment:
      - DATABASE_TYPE=sqlite
      - DATABASE_PATH=/data/video_memory.db  # Absolute path!
      - ORCHESTRATOR_PORT=8080
      - LOG_LEVEL=info
    volumes:
      - ~/Mnemo/data:/data  # Mount data directory
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 300M
          cpus: '0.5'
        reservations:
          memory: 200M
    
  video-worker:
    image: mnemo_video_worker:latest
    environment:
      - DATABASE_PATH=/data/video_memory.db
      - LOG_LEVEL=info
    volumes:
      - ~/Mnemo/data:/data  # Same data directory
    restart: unless-stopped
    depends_on:
      - orchestrator
    deploy:
      resources:
        limits:
          memory: 500M
          cpus: '0.5'
        reservations:
          memory: 300M
          
  motion-extractor:
    image: mnemo_motion_extractor:latest
    environment:
      - DATABASE_PATH=/data/video_memory.db
      - LOG_LEVEL=info
    volumes:
      - ~/Mnemo/data:/data
    restart: unless-stopped
    depends_on:
      - video-worker
    deploy:
      resources:
        limits:
          memory: 600M
          cpus: '0.5'
        reservations:
          memory: 400M